/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.nyce.moves;

import java.math.BigDecimal;
import com.nyce.moves.ModelApiResponse;
import com.nyce.moves.Player;
import com.nyce.moves.PlayerRequest;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-19T16:41:29.282+05:30")

@Api(value = "players", description = "the players API")
public interface PlayersApi {

    @ApiOperation(value = "Player Registeration", nickname = "createPlayer", notes = "Player registeration into the system.", tags={ "players", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/players",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> createPlayer(@ApiParam(value = "Created user object" ,required=true )  @Valid @RequestBody PlayerRequest body);


    @ApiOperation(value = "Delete player", nickname = "deletePlayer", notes = "Delete Player Account.", response = ModelApiResponse.class, tags={ "players", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = ModelApiResponse.class),
        @ApiResponse(code = 400, message = "Invalid username supplied"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/players/{playerId}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    ResponseEntity<ModelApiResponse> deletePlayer(@ApiParam(value = "The playerId that needs to be deleted",required=true) @PathVariable("playerId") String playerId);


    @ApiOperation(value = "Get the details of a player based on player id session", nickname = "getPlayer", notes = "Player Information.", tags={ "players", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/players/{playerId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> getPlayer(@ApiParam(value = "The playerId of the current player",required=true) @PathVariable("playerId") Integer playerId,@ApiParam(value = "", defaultValue = "10") @Valid @RequestParam(value = "pageSize", required = false, defaultValue="10") BigDecimal pageSize,@ApiParam(value = "", defaultValue = "1") @Valid @RequestParam(value = "pageNumber", required = false, defaultValue="1") BigDecimal pageNumber);


    @ApiOperation(value = "Logs player into the system", nickname = "loginUser", notes = "", tags={ "players", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 400, message = "Invalid username/password supplied") })
    @RequestMapping(value = "/players/login",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Void> loginUser(@ApiParam(value = "The user name for login" ,required=true) @RequestHeader(value="username", required=true) String username,@ApiParam(value = "The password for login in clear text" ,required=true) @RequestHeader(value="password", required=true) String password);


    @ApiOperation(value = "Logs out current logged in player session", nickname = "logoutUser", notes = "", response = ModelApiResponse.class, tags={ "players", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = ModelApiResponse.class) })
    @RequestMapping(value = "/players/{playerId}/logout",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ModelApiResponse> logoutUser(@ApiParam(value = "The playerId of the current player",required=true) @PathVariable("playerId") Integer playerId);


    @ApiOperation(value = "Updated player", nickname = "updatePlayer", notes = "This can only be done by the logged in player.", tags={ "players", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 400, message = "Invalid Player supplied"),
        @ApiResponse(code = 404, message = "Player not found") })
    @RequestMapping(value = "/players/{playerId}",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> updatePlayer(@ApiParam(value = "player that need to be updated",required=true) @PathVariable("playerId") String playerId,@ApiParam(value = "Updated player object" ,required=true )  @Valid @RequestBody Player body);

}
